# Generated by Django 3.1.2 on 2020-10-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201012_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
