# Generated by Django 3.1.2 on 2020-10-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=models.CharField(max_length=500),
        ),
    ]
